### PR TITLE
added HOOK macro

### PR DESCRIPTION
**Pull request by Rednick16**
Its all about making life easy.

### CODE REVIEW

**Comment by RiTHPUBG** [comment]
Thanks

**Comment by Mahmoud-GMG** [comment]
Bro It is a good idea but it crashs in my 8 ball pool mod
you tested before posting ??

**Comment by Rednick16** [comment]
> Bro It is a good idea but it crashs in my 8 ball pool mod
> you tested before posting ??

How did you write it?
you have to write it like this 
HOOK(“offset”, ptr, _ptr); the offset gets encrypted already

**Comment by Mahmoud-GMG** [comment]
I did that bro 😊

**Comment by Rednick16** [comment]
> I did that bro 😊
> […](#)

I did test it, it worked for me, make sure your not entering the wrong offsets. You could also try to use MSHookFunction. Also you still need to delete extra folders for what ever version of the game ur modding and keep only that folder lets say im modding armv7 i will delete all other folders except that folder etc..

**Comment by Mahmoud-GMG** [comment]
I know bro
I think that is from game's protection
I have right offset

**Comment by LGLTeam** [comment]
@Rednick16 You should use new obfuscate key like `OBFUSCATE_KEY("0x222222", 23479432523588)`

**Comment by Rednick16** [comment]
> @Rednick16 You should use new obfuscate key in 64-bit like `OBFUSCATE_KEY("0x222222", 23479432523588)`

Alright i will Update HOOK macro it’s probably best to not add obfuscation to it since all the keys would be the same and it would be easier for some one to leech

**Comment by LGLTeam** [comment]
> > @Rednick16 You should use new obfuscate key in 64-bit like `OBFUSCATE_KEY("0x222222", 23479432523588)`
> 
> Alright i will Update HOOK macro it’s probably best to not add obfuscation to it since all the keys would be the same and it would be easier for some one to leech
Thanks
I use it as an example. They could make their own protection if they want better protection

**Comment by Siddu-Modder** [comment]
@LGLTeam PLEASE OWNER CAN YOU TELL HOW TO CHANGE CORNER SIZE IN ANDROID MOD MENU TEMPLATE BECAUSE WHEN I CHANGING ITS CORNER ITS BIT CHANGING...

PLEASE HELP ME 🥺🥺🥺🥺🥺

**Pull request merged**
