### PR TITLE
new feature type

### PR DESCRIPTION
**Pull request by T5ive**
InputOnOff (TextField+ButtonOnOff) *Change the value with a long press
InputButton (TextField+Button) *Change the value with a long press
SeekBarSwitch (SeekBar+Switch)

### CODE REVIEW

**Comment by T5ive** [comment]
ex
https://user-images.githubusercontent.com/41800233/122244576-319fe480-ceef-11eb-9f63-e4e95d57200c.mp4

**Comment by LGLTeam** [comment]
Great work but it will make the project more overcomplicated. I will think about it

**Review by LGLTeam — APPROVED** [review]

**Review by LGLTeam — APPROVED** [review]
Minor changes like change feature to featNum will be approved
InputButton will be approved. It can be useful for adding in-game money

**Review by LGLTeam — COMMENTED** [review]
I have made a decision. This will not be approved. It is a design flaw and too complicated to work with, and i don't see it benifit for everyone, modder could just add an extra switch if they want to switch the feature. And at least use collapse if it takes spaces

**Comment by LGLTeam** [comment]
After checking the code and testing very carefully, and thinking about design, i have make a decision that InputButton will not be added. The code is quite broken, and long press to change value can fuck up the muscle memory

In any case, you need add money with custom value or whatever, just add another button below Inputvalue which calls the code to add something. This is significant better, without confusion between long pressing and clicking

Your contribution is still great, it just that the design and features doesn't fit for me. You are still welcome to make another PR of other changes, and i will check whether to merge or not

This will be merged due to minor changes, but the features will be removed in the next commit

**Pull request merged**
